[package]
name = "paprun"
version = "0.1.0"
edition = "2024"
description = "Interpreter für die XML-Pseudocodes der BMF-Programmablaufpläne (Lohnsteuer)"
license = "MIT"

[dependencies]
bigdecimal = "0.4"
csv = "1.4.0"
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
roxmltree = "0.20"

[profile.release]
lto = true
codegen-units = 1
